// models/shortUrl.js

import mongoose from 'mongoose';
import { nanoid } from 'nanoid';

// Define the schema for the short URL
const shortUrlSchema = new mongoose.Schema({
  full: {
    type: String,
    required: true,
  },
  short: {
    type: String,
    required: true,
    unique: true,
    default: () => nanoid(7),  // Default value is generated by nanoid
  },
  clicks: {
    type: Number,
    default: 0,
  },
});

// Export the model
const ShortUrl = mongoose.model('ShortUrls', shortUrlSchema);
export default ShortUrl;  // Export using ES module syntax
